### ISSUE TITLE
expiration datetime

### ISSUE THREAD

**Issue by kaerdsar** [yelizariev/odoo-saas-tools#8]
The expiration datetime is setted to a new client from the saas_portal.plan data. The command /saas_server/synch_data only get data, don't update the server. Exists any case where you need to modify the expiration_datetime of a client from saas_portal to update in saas_server?

**Comment by kaerdsar** [comment]
Yesterday I added a cron in saas_server addon to delete expired databases. Today I discover the addon saas_server_autodelete. Do you want to separate the autodelete function from saas_server addon? In that case, we must at least show a warning to know is there a database expired if you do not use saas_server_autodelete? Do you want to have differents actions when a database expire (eg, delete, cancel)? If you want to a client pay for his tenant you may cancel when expire but no delete the database, so re-enable the database later. Tell me your idea to implement in the correct way.

**Comment by yelizariev** [comment]
I create a separate module saas_server_autodelete to be sure, that SaaS owner understand that databases will be deleted automatically.

We could show warning at top message (instead of message it will be destoyed in 3 hours if some is passed).

We don't need other actions now, because our current target is prepare saas system for demo.

The same about sending expiration_datetime from saas_portal to saas_server (e.g. when customer paid for service and administrator remove expiration_datetime) -- we don't need it for demo. Currently,  expiration_datetime should be set on server when we create new database.
